In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
student_performance = fetch_ucirepo(id=320)

# data (as pandas dataframes)
X = student_performance.data.features
y = student_performance.data.targets

# metadata
print(student_performance.metadata)

# variable information
print(student_performance.variables)

{'uci_id': 320, 'name': 'Student Performance', 'repository_url': 'https://archive.ics.uci.edu/dataset/320/student+performance', 'data_url': 'https://archive.ics.uci.edu/static/public/320/data.csv', 'abstract': 'Predict student performance in secondary education (high school). ', 'area': 'Social Science', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 649, 'num_features': 30, 'feature_types': ['Integer'], 'demographics': ['Sex', 'Age', 'Other', 'Education Level', 'Occupation'], 'target_col': ['G1', 'G2', 'G3'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2008, 'last_updated': 'Fri Jan 05 2024', 'dataset_doi': '10.24432/C5TG7T', 'creators': ['Paulo Cortez'], 'intro_paper': {'ID': 360, 'type': 'NATIVE', 'title': 'Using data mining to predict secondary school student performance', 'authors': 'P. Cortez, A. M. G. Silva', 'venue': 'Proceedings of 5th Annual Future Business Technology Conference', 'year': 2008, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/61d468d5254730bbecf822c6b60d7d6595d9889c', 'sha': None, 'corpus': '16621299', 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This data approach student achievement in secondary education of two Portuguese schools. The data attributes include student grades, demographic, social and school related features) and it was collected by using school reports and questionnaires. Two datasets are provided regarding the performance in two distinct subjects: Mathematics (mat) and Portuguese language (por). In [Cortez and Silva, 2008], the two datasets were modeled under binary/five-level classification and regression tasks. Important note: the target attribute G3 has a strong correlation with attributes G2 and G1. This occurs because G3 is the final year grade (issued at the 3rd period), while G1 and G2 correspond to the 1st and 2nd period grades. It is more difficult to predict G3 without G2 and G1, but such prediction is much more useful (see paper source for more details).', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "# Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:\r\n1 school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)\r\n2 sex - student's sex (binary: 'F' - female or 'M' - male)\r\n3 age - student's age (numeric: from 15 to 22)\r\n4 address - student's home address type (binary: 'U' - urban or 'R' - rural)\r\n5 famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)\r\n6 Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)\r\n7 Medu - mother's education (numeric: 0 - none,  1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)\r\n8 Fedu - father's education (numeric: 0 - none,  1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)\r\n9 Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')\r\n10 Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')\r\n11 reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')\r\n12 guardian - student's guardian (nominal: 'mother', 'father' or 'other')\r\n13 traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)\r\n14 studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)\r\n15 failures - number of past class failures (numeric: n if 1<=n<3, else 4)\r\n16 schoolsup - extra educational support (binary: yes or no)\r\n17 famsup - family educational support (binary: yes or no)\r\n18 paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)\r\n19 activities - extra-curricular activities (binary: yes or no)\r\n20 nursery - attended nursery school (binary: yes or no)\r\n21 higher - wants to take higher education (binary: yes or no)\r\n22 internet - Internet access at home (binary: yes or no)\r\n23 romantic - with a romantic relationship (binary: yes or no)\r\n24 famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)\r\n25 freetime - free time after school (numeric: from 1 - very low to 5 - very high)\r\n26 goout - going out with friends (numeric: from 1 - very low to 5 - very high)\r\n27 Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)\r\n28 Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)\r\n29 health - current health status (numeric: from 1 - very bad to 5 - very good)\r\n30 absences - number of school absences (numeric: from 0 to 93)\r\n\r\n# these grades are related with the course subject, Math or Portuguese:\r\n31 G1 - first period grade (numeric: from 0 to 20)\r\n31 G2 - second period grade (numeric: from 0 to 20)\r\n32 G3 - final grade (numeric: from 0 to 20, output target)", 'citation': None}}
          name     role         type      demographic  \
0       school  Feature  Categorical             None
1          sex  Feature       Binary              Sex
2          age  Feature      Integer              Age
3      address  Feature  Categorical             None
4      famsize  Feature  Categorical            Other
5      Pstatus  Feature  Categorical            Other
6         Medu  Feature      Integer  Education Level
7         Fedu  Feature      Integer  Education Level
8         Mjob  Feature  Categorical       Occupation
9         Fjob  Feature  Categorical       Occupation
10      reason  Feature  Categorical             None
11    guardian  Feature  Categorical             None
12  traveltime  Feature      Integer             None
13   studytime  Feature      Integer             None
14    failures  Feature      Integer             None
15   schoolsup  Feature       Binary             None
16      famsup  Feature       Binary             None
17        paid  Feature       Binary             None
18  activities  Feature       Binary             None
19     nursery  Feature       Binary             None
20      higher  Feature       Binary             None
21    internet  Feature       Binary             None
22    romantic  Feature       Binary             None
23      famrel  Feature      Integer             None
24    freetime  Feature      Integer             None
25       goout  Feature      Integer             None
26        Dalc  Feature      Integer             None
27        Walc  Feature      Integer             None
28      health  Feature      Integer             None
29    absences  Feature      Integer             None
30          G1   Target  Categorical             None
31          G2   Target  Categorical             None
32          G3   Target      Integer             None

                                          description units missing_values
0   student's school (binary: 'GP' - Gabriel Perei...  None             no
1   student's sex (binary: 'F' - female or 'M' - m...  None             no
2              student's age (numeric: from 15 to 22)  None             no
3   student's home address type (binary: 'U' - urb...  None             no
4   family size (binary: 'LE3' - less or equal to ...  None             no
5   parent's cohabitation status (binary: 'T' - li...  None             no
6   mother's education (numeric: 0 - none,  1 - pr...  None             no
7   father's education (numeric: 0 - none,  1 - pr...  None             no
8   mother's job (nominal: 'teacher', 'health' car...  None             no
9   father's job (nominal: 'teacher', 'health' car...  None             no
10  reason to choose this school (nominal: close t...  None             no
11  student's guardian (nominal: 'mother', 'father...  None             no
12  home to school travel time (numeric: 1 - <15 m...  None             no
13  weekly study time (numeric: 1 - <2 hours, 2 - ...  None             no
14  number of past class failures (numeric: n if 1...  None             no
15      extra educational support (binary: yes or no)  None             no
16     family educational support (binary: yes or no)  None             no
17  extra paid classes within the course subject (...  None             no
18    extra-curricular activities (binary: yes or no)  None             no
19        attended nursery school (binary: yes or no)  None             no
20  wants to take higher education (binary: yes or...  None             no
21        Internet access at home (binary: yes or no)  None             no
22   with a romantic relationship (binary: yes or no)  None             no
23  quality of family relationships (numeric: from...  None             no
24  free time after school (numeric: from 1 - very...  None             no
25  going out with friends (numeric: from 1 - very...  None             no
26  workday alcohol consumption (numeric: from 1 -...  None             no
27  weekend alcohol consumption (numeric: from 1 -...  None             no
28  current health status (numeric: from 1 - very ...  None             no
29  number of school absences (numeric: from 0 to 93)  None             no
30         first period grade (numeric: from 0 to 20)  None             no
31        second period grade (numeric: from 0 to 20)  None             no
32  final grade (numeric: from 0 to 20, output tar...  None             no

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
#clean the data set
X.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
dtypes: int64(13), object(17)
memory usage: 152.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   G1      649 non-null    int64
 1   G2      649 non-null    int64
 2   G3      649 non-null    int64
dtypes: int64(3)
memory usage: 15.3 KB

In [12]:
X.describe()
y.describe()

               G1          G2          G3
count  649.000000  649.000000  649.000000
mean    11.399076   11.570108   11.906009
std      2.745265    2.913639    3.230656
min      0.000000    0.000000    0.000000
25%     10.000000   10.000000   10.000000
50%     11.000000   11.000000   12.000000
75%     13.000000   13.000000   14.000000
max     19.000000   19.000000   19.000000

In [15]:
display(X.head())
display(y.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,2
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,6
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,0

   G1  G2  G3
0   0  11  11
1   9  11  11
2  12  13  12
3  14  14  14
4  11  13  13

In [25]:
#drop null values in both X and y
X.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
dtype: int64

In [26]:
y.isna().sum()

G1    0
G2    0
G3    0
dtype: int64

In [27]:
X.duplicated().sum()

np.int64(0)

In [28]:
y.duplicated().sum()

np.int64(456)

In [31]:
q1, q3 = X['age'].quantile([0.25, 0.75])
iqr = q3 - q1
print(iqr)

2.0

In [32]:
#find how many teachers are females
X['Fjob']= 'teacher'
print(X['Fjob'])
print(X.value_counts())

0      teacher
1      teacher
2      teacher
3      teacher
4      teacher
        ...
644    teacher
645    teacher
646    teacher
647    teacher
648    teacher
Name: Fjob, Length: 649, dtype: object
school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob      Fjob     reason      guardian  traveltime  studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences
MS      M    20   R        GT3      T        1     1     other     teacher  course      other     2           1          1         no         yes     no    no          yes      no      yes       yes       4       4         3      2     4     4       12          1
GP      F    15   R        GT3      T        1     1     at_home   teacher  home        mother    2           4          0         yes        yes     yes   yes         yes      yes     yes       no        3       1         2      1     1     1       4           1
                                                         other     teacher  course      mother    3           1          1         no         no      no    yes         yes      yes     yes       yes       5       5         5      1     1     1       2           1
                                                                            reputation  mother    1           2          0         yes        yes     no    no          no       yes     yes       yes       3       3         4      2     4     5       2           1
                                             2     2     at_home   teacher  reputation  mother    1           1          0         yes        yes     no    yes         yes      yes     no        no        4       3         1      1     1     2       8           1
                                                                                                                                                                                                                                                                     ..
                  U        GT3      T        1     1     at_home   teacher  course      mother    3           1          0         no         yes     no    yes         no       yes     yes       yes       4       3         3      1     2     4       6           1
                                    A        4     3     services  teacher  reputation  mother    1           2          0         no         yes     no    yes         yes      yes     yes       no        4       3         2      1     1     1       0           1
                                             3     3     services  teacher  home        mother    1           2          0         no         no      no    no          no       yes     no        yes       1       3         2      2     3     1       24          1
                                                         other     teacher  reputation  father    1           4          0         yes        no      no    no          yes      yes     no        no        4       3         3      1     1     4       10          1
                  R        LE3      T        3     1     other     teacher  reputation  father    2           4          0         no         yes     no    no          no       yes     yes       no        4       4         2      2     3     3       6           1
Name: count, Length: 649, dtype: int64

/tmp/ipykernel_8313/359233338.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Fjob']= 'teacher'